name: Run Modified Solutions on Public Set

on:
  pull_request:
    branches: 
      - main

jobs:
  main:
    strategy:
      matrix:
        pack: [...]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run
      run: |
        inv test-modified-solutions --input-id ${{ matrix.pack }} --fail