name: Run Modified Solutions

on:
  pull_request:
    branches: 
      - main
  push:
    branches:
      - main

jobs:
  main:
    strategy:
      matrix:
        pack: [...]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v1
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install erudition
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-region: eu-central-1
    - name: Run
      run: |
        inv test-modified-solutions --input-id ${{ matrix.pack }}
